services:
  # Adminer
  # MySQL
  # SQLite 3
  # SQLite 2
  # PostgreSQL
  # Oracle (beta)
  # MS SQL (beta)
  # MongoDB (alpha)
  # Elasticsearch (beta)
  adminer:
    image: adminer
    ports:
      - "8081:8080"
    networks:
      - backend

  # MySQL
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./databases/mysql/service/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend

  # MongoDB
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongodb:/data/db
      - ./databases/mongodb/service/init.js:/docker-entrypoint-initdb.d/mongo-init.js
    networks:
      - backend

  # PostgreSQL
  postgresql:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
      - ./databases/postgresql/service/init.pgsql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend

  # PostgreSQL UI (pgAdmin)
  postgresql_ui:
    image: dpage/pgadmin4
    ports:
      - "8082:10304"
    volumes:
      - ./databases/postgresql/service-ui/servers.json:/pgadmin4/servers.json
    environment:
      PGADMIN_DEFAULT_EMAIL: "${POSTGRES_USER}@${DOMAIN}"
      PGADMIN_DEFAULT_PASSWORD: "${POSTGRES_PASSWORD}"
    depends_on:
      - postgresql
    networks:
      - backend

  # Cassandra
  cassandra:
    image: cassandra
    environment:
      CASSANDRA_CLUSTER_NAME: ${CASSANDRA_CLUSTER_NAME}
      CASSANDRA_NUM_TOKENS: 16
      CASSANDRA_RPC_ADDRESS: 0.0.0.0
    ports:
      - "9042:9042"
    volumes:
      - ./data/cassandra:/var/lib/cassandra
      - ./databases/cassandra/service/init.cql:/docker-entrypoint-initdb.d/init.cql
    networks:
      - backend

  # ClickHouse
  clickhouse:
    image: yandex/clickhouse-server
    ports:
      - "8123:8123"
      - "9001:9000"
    volumes:
      - ./data/clickhouse:/var/lib/clickhouse
      - ./databases/clickhouse/service/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend

  # Redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    networks:
      - backend

  # InfluxDB
  influxdb:
    image: influxdb
    ports:
      - "8086:8086"
    environment:
      INFLUXDB_DB: ${INFLUXDB_DB}
      INFLUXDB_ADMIN_USER: ${INFLUXDB_ADMIN_USER}
      INFLUXDB_ADMIN_PASSWORD: ${INFLUXDB_ADMIN_PASSWORD}
    volumes:
      - ./data/influxdb:/var/lib/influxdb
    networks:
      - backend

  # Elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # Memory
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - backend

  # Neo4j
  neo4j:
    image: neo4j:4.4
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD}
    ports:
      - "7474:7474" # Neo4j Browser UI
      - "7687:7687" # Bolt Protocol Port
    volumes:
      - ./data/neo4j:/data
    networks:
      - backend

  # HDFS (Hadoop NameNode)
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    environment:
      - CLUSTER_NAME=hadoop
    ports:
      - "9870:9870" # Namenode Web UI
      - "9000:9000"
    volumes:
      - ./data/hdfs:/hadoop/dfs/name
    networks:
      - backend

  # CouchDB
  couchdb:
    image: couchdb:latest
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
    volumes:
      - ./data/couchdb:/opt/couchdb/data
    networks:
      - backend

networks:
  backend:
    driver: bridge
