-- 7. Örnek Veri Ekleme: Kategoriler
INSERT INTO categories (category_name, description) VALUES
    ('News', 'Latest news updates including politics, economy, and current events'),
    ('Social Media', 'Trends and viral content from social media platforms'),
    ('Trends', 'Trending topics globally and locally, including seasonal trends'),
    ('Finance', 'Financial data including stock market trends and cryptocurrency'),
    ('Entertainment', 'Updates on TV shows, music, and entertainment events'),
    ('Technology & Science', 'Information on technological advancements and scientific research'),
    ('Health & Medicine', 'Health-related data including treatments and medical research'),
    ('Sports', 'Updates on various sports, e-sports, and sporting events'),
    ('E-commerce & Products', 'Trends in products and online shopping insights'),
    ('Education & Research', 'Data for educational purposes and online courses'),
    ('Cryptocurrency', 'Information related to cryptocurrencies and blockchain technology'),
    ('Applications', 'Trends in mobile and desktop applications'),
    ('Movies', 'Data related to films including reviews and box office reports'),
    ('Books', 'Trends in literature and publishing'),
    ('Games', 'Updates from the gaming industry including video and board games'),
    ('Fashion', 'Trends in the clothing and fashion industry'),
    ('Travel', 'Travel-related news and updates'),
    ('Food & Drink', 'Trends in food and beverage industries'),
    ('Environment', 'Environmental issues and sustainability trends');