-- 12. Örnek Veri Ekleme: Veri Kaynakları
INSERT INTO data_sources (source_name, source_url, category_id, data_type_id, access_method_id, reliability_id, freshness_id) VALUES
    ('Wikipedia New Pages', 'https://en.wikipedia.org/w/index.php?title=Special:NewPages&feed=rss', 
    (SELECT category_id FROM categories WHERE category_name = 'Trends'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'RSS'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'High'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Continuous')),

    ('Google Trends (RSS)', 'https://trends.google.com/trending/rss?geo=US', 
    (SELECT category_id FROM categories WHERE category_name = 'Trends'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'RSS'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'High'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Daily')),

    ('Google Trends (Web)', 'https://trends.google.com/trending?geo=US', 
    (SELECT category_id FROM categories WHERE category_name = 'Trends'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'High'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Daily')),

    ('Google Alerts', 'https://www.google.com/alerts', 
    (SELECT category_id FROM categories WHERE category_name = 'News'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'RSS'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'High'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Daily')),

    ('YouTube Trending', 'https://www.youtube.com/feed/trending', 
    (SELECT category_id FROM categories WHERE category_name = 'Social Media'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'High'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Daily')),

    ('Facebook News', 'https://about.fb.com/news/', 
    (SELECT category_id FROM categories WHERE category_name = 'News'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'High'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Daily')),

    ('Instagram Explore', 'https://www.instagram.com/explore/?hl=en', 
    (SELECT category_id FROM categories WHERE category_name = 'Social Media'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'High'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Continuous')),

    ('Twitter Trends', 'https://twitter.com/explore/tabs/trending', 
    (SELECT category_id FROM categories WHERE category_name = 'Social Media'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'High'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Continuous')),

    ('Reddit', 'https://www.reddit.com/.rss', 
    (SELECT category_id FROM categories WHERE category_name = 'Social Media'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'RSS'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'Medium'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Continuous')),

    ('Reddit News', 'https://www.reddit.com/r/news/.rss', 
    (SELECT category_id FROM categories WHERE category_name = 'News'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'RSS'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'Medium'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Continuous')),

    ('Reddit Cryptocurrency', 'https://www.reddit.com/r/CryptoCurrency/.rss', 
    (SELECT category_id FROM categories WHERE category_name = 'Cryptocurrency'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'RSS'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'Medium'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Continuous')),

    ('Pinterest Trends', 'https://trends.pinterest.com/', 
    (SELECT category_id FROM categories WHERE category_name = 'Social Media'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'Medium'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Continuous')),

    ('Google Play Apps', 'https://play.google.com/store/apps?hl=en', 
    (SELECT category_id FROM categories WHERE category_name = 'Applications'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'High'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Continuous')),

    ('Google Play Movies', 'https://play.google.com/store/movies?hl=en', 
    (SELECT category_id FROM categories WHERE category_name = 'Movies'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'High'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Continuous')),

    ('Google Play Books', 'https://play.google.com/store/books?hl=en', 
    (SELECT category_id FROM categories WHERE category_name = 'Books'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'High'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Continuous')),

    ('Google Play Games', 'https://play.google.com/store/games?hl=en', 
    (SELECT category_id FROM categories WHERE category_name = 'Games'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'High'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Continuous')),    

    ('MSN News', 'https://www.msn.com/', 
    (SELECT category_id FROM categories WHERE category_name = 'News'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'High'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Daily')),

    ('Amazon', 'https://www.amazon.com/', 
    (SELECT category_id FROM categories WHERE category_name = 'E-commerce'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'High'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Continuous')),

    ('TikTok Explore', 'https://www.tiktok.com/explore', 
    (SELECT category_id FROM categories WHERE category_name = 'Social Media'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'Medium'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Continuous')),

    ('IMDb TV News', 'https://www.imdb.com/news/tv/?ref_=nv_nw_tv', 
    (SELECT category_id FROM categories WHERE category_name = 'Movies'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'High'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Daily')),

    ('IMDb Movie News', 'https://www.imdb.com/news/movie/?ref_=nv_nw_mv', 
    (SELECT category_id FROM categories WHERE category_name = 'Movies'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'High'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Daily')),

    ('Weather', 'https://weather.com/', 
    (SELECT category_id FROM categories WHERE category_name = 'Weather'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'High'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Daily')),

    ('CoinMarketCap', 'https://coinmarketcap.com/', 
    (SELECT category_id FROM categories WHERE category_name = 'Cryptocurrency'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'High'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Continuous')),

    ('CoinGecko', 'https://www.coingecko.com/en', 
    (SELECT category_id FROM categories WHERE category_name = 'Cryptocurrency'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'High'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Continuous')),

    ('Cryptopanic', 'https://cryptopanic.com/', 
    (SELECT category_id FROM categories WHERE category_name = 'Cryptocurrency'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'Medium'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Continuous')),

    ('CoinTelegraph', 'https://cointelegraph.com/', 
    (SELECT category_id FROM categories WHERE category_name = 'Cryptocurrency'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'Medium'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Continuous')),

    ('DailyFX', 'https://www.dailyfx.com/', 
    (SELECT category_id FROM categories WHERE category_name = 'Forex'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'Medium'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Continuous')),

    ('FXStreet', 'https://www.fxstreet.com/', 
    (SELECT category_id FROM categories WHERE category_name = 'Forex'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'Medium'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Continuous')),

    ('TradingView', 'https://www.tradingview.com/', 
    (SELECT category_id FROM categories WHERE category_name = 'Forex'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'Medium'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Continuous')),

    ('Bloomberg', 'https://www.bloomberg.com/', 
    (SELECT category_id FROM categories WHERE category_name = 'Finance'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'High'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Daily')),

    ('Reuters', 'https://www.reuters.com/', 
    (SELECT category_id FROM categories WHERE category_name = 'News'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'High'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Daily')),

    ('Hacker News', 'https://news.ycombinator.com/', 
    (SELECT category_id FROM categories WHERE category_name = 'Technology'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'Medium'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Continuous')),

    ('TechCrunch', 'https://techcrunch.com/', 
    (SELECT category_id FROM categories WHERE category_name = 'Technology'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'High'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Daily')),

    ('The Verge', 'https://www.theverge.com/', 
    (SELECT category_id FROM categories WHERE category_name = 'Technology'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'High'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Daily')),

    ('Gizmodo', 'https://gizmodo.com/', 
    (SELECT category_id FROM categories WHERE category_name = 'Technology'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'Medium'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Continuous')),

    ('CNET', 'https://www.cnet.com/', 
    (SELECT category_id FROM categories WHERE category_name = 'Technology'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'Medium'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Daily')),

    ('Engadget', 'https://www.engadget.com/', 
    (SELECT category_id FROM categories WHERE category_name = 'Technology'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'Medium'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Daily')),

    ('Mashable', 'https://mashable.com/', 
    (SELECT category_id FROM categories WHERE category_name = 'Technology'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'Medium'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Daily')),

    ('Vice', 'https://www.vice.com/en_us', 
    (SELECT category_id FROM categories WHERE category_name = 'News'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'Medium'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Daily')),

    ('The Guardian', 'https://www.theguardian.com/international', 
    (SELECT category_id FROM categories WHERE category_name = 'News'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'High'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Daily')),

    ('New York Times', 'https://www.nytimes.com/', 
    (SELECT category_id FROM categories WHERE category_name = 'News'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'High'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Daily')),

    ('NPR', 'https://www.npr.org/', 
    (SELECT category_id FROM categories WHERE category_name = 'News'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'High'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Daily')),

    ('BBC', 'https://www.bbc.co.uk/news', 
    (SELECT category_id FROM categories WHERE category_name = 'News'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'High'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Daily')),

    ('Al Jazeera', 'https://www.aljazeera.com/', 
    (SELECT category_id FROM categories WHERE category_name = 'News'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'High'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Daily')),

    ('CNN', 'https://www.cnn.com/', 
    (SELECT category_id FROM categories WHERE category_name = 'News'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'High'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Daily')),

    ('Forbes', 'https://www.forbes.com/', 
    (SELECT category_id FROM categories WHERE category_name = 'Finance'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'High'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Daily')),

    ('The Hill', 'https://thehill.com/', 
    (SELECT category_id FROM categories WHERE category_name = 'News'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'Medium'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Daily'))
);


INSERT INTO data_sources (source_name, source_url, category_id, data_type_id, access_method_id, reliability_id, freshness_id) VALUES
    ('CoinMarketCap', 'https://coinmarketcap.com', 
    (SELECT category_id FROM categories WHERE category_name = 'Cryptocurrency'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'High'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Continuous')),
    
    ('Top Charts - App Store', 'https://apps.apple.com/us/charts/iphone', 
    (SELECT category_id FROM categories WHERE category_name = 'Applications'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'High'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Continuous')),
    
    ('Rotten Tomatoes', 'https://www.rottentomatoes.com/', 
    (SELECT category_id FROM categories WHERE category_name = 'Movies'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'High'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Daily')),
    
    ('Goodreads', 'https://www.goodreads.com/', 
    (SELECT category_id FROM categories WHERE category_name = 'Books'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'High'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Daily')),
    
    ('Steam', 'https://store.steampowered.com/', 
    (SELECT category_id FROM categories WHERE category_name = 'Games'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'High'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Continuous')),
    
    ('Vogue', 'https://www.vogue.com/', 
    (SELECT category_id FROM categories WHERE category_name = 'Fashion'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'Medium'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Daily')),
    
    ('National Geographic', 'https://www.nationalgeographic.com/', 
    (SELECT category_id FROM categories WHERE category_name = 'Environment'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'High'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Daily')),
    
    ('TripAdvisor', 'https://www.tripadvisor.com/', 
    (SELECT category_id FROM categories WHERE category_name = 'Travel'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'Medium'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Continuous')),
    
    ('Food Network', 'https://www.foodnetwork.com/', 
    (SELECT category_id FROM categories WHERE category_name = 'Food & Drink'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'Medium'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Daily'));

-- 12. Örnek Veri Ekleme: Veri Kaynakları
INSERT INTO data_sources (source_name, source_url, category_id, data_type_id, access_method_id, reliability_id, freshness_id) VALUES
    ('Wikipedia New Pages', 'https://en.wikipedia.org/w/index.php?title=Special:NewPages&feed=rss', 
    (SELECT category_id FROM categories WHERE category_name = 'Trends'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'RSS'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'High'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Continuous')),
    
    ('Google Trends (RSS)', 'https://trends.google.com/trending/rss?geo=US', 
    (SELECT category_id FROM categories WHERE category_name = 'Trends'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'RSS'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'High'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Daily')),
    
    ('Google Trends (Web)', 'https://trends.google.com/trending?geo=US', 
    (SELECT category_id FROM categories WHERE category_name = 'Trends'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'High'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Daily')),
    
    ('Google Alerts', 'https://www.google.com/alerts', 
    (SELECT category_id FROM categories WHERE category_name = 'News'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'RSS'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'High'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Daily')),
    
    ('YouTube Trending', 'https://www.youtube.com/feed/trending', 
    (SELECT category_id FROM categories WHERE category_name = 'Social Media'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'High'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Daily')),
    
    ('Facebook News', 'https://about.fb.com/news/', 
    (SELECT category_id FROM categories WHERE category_name = 'News'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'High'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Daily')),
    
    ('Instagram Explore', 'https://www.instagram.com/explore/?hl=en', 
    (SELECT category_id FROM categories WHERE category_name = 'Social Media'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'High'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Continuous')),
    
    ('Twitter Trends', 'https://twitter.com/explore/tabs/trending', 
    (SELECT category_id FROM categories WHERE category_name = 'Social Media'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'High'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Continuous')),
    
    ('Reddit', 'https://www.reddit.com/.rss', 
    (SELECT category_id FROM categories WHERE category_name = 'Social Media'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'RSS'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'Medium'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Continuous')),
    
    ('Reddit News', 'https://www.reddit.com/r/news/.rss', 
    (SELECT category_id FROM categories WHERE category_name = 'Social Media'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'RSS'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'Medium'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Continuous')),
    
    ('Reddit Cryptocurrency', 'https://www.reddit.com/r/CryptoCurrency/.rss', 
    (SELECT category_id FROM categories WHERE category_name = 'Trends'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'RSS'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'Medium'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Continuous')),
    
    ('Pinterest Trends', 'https://trends.pinterest.com/', 
    (SELECT category_id FROM categories WHERE category_name = 'Social Media'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'Medium'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Continuous')),
    
    ('Google Play Apps', 'https://play.google.com/store/apps?hl=en', 
    (SELECT category_id FROM categories WHERE category_name = 'Applications'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'High'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Continuous')),
    
    ('Google Play Movies', 'https://play.google.com/store/movies?hl=en', 
    (SELECT category_id FROM categories WHERE category_name = 'Entertainment'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'High'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Continuous')),
    
    ('Google Play Books', 'https://play.google.com/store/books?hl=en', 
    (SELECT category_id FROM categories WHERE category_name = 'Education & Research'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'High'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Continuous')),
    
    ('Google Play Games', 'https://play.google.com/store/games?hl=en', 
    (SELECT category_id FROM categories WHERE category_name = 'Entertainment'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'High'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Continuous')),
    
    ('Apple Charts', 'https://apps.apple.com/us/charts/iphone', 
    (SELECT category_id FROM categories WHERE category_name = 'Applications'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'High'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Continuous')),
    
    ('MSN News', 'https://www.msn.com/', 
    (SELECT category_id FROM categories WHERE category_name = 'News'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'High'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Daily')),
    
    ('Amazon', 'https://www.amazon.com/', 
    (SELECT category_id FROM categories WHERE category_name = 'E-commerce & Products'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'High'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Daily')),
    
    ('LinkedIn', 'https://www.linkedin.com/feed/', 
    (SELECT category_id FROM categories WHERE category_name = 'Social Media'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'Medium'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Daily')),
    
    ('Quora', 'https://www.quora.com/feed', 
    (SELECT category_id FROM categories WHERE category_name = 'Education & Research'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'High'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Daily')),
    
    ('Bing', 'https://www.bing.com/news', 
    (SELECT category_id FROM categories WHERE category_name = 'News'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'High'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Daily')),
    
    ('TikTok', 'https://www.tiktok.com/trending', 
    (SELECT category_id FROM categories WHERE category_name = 'Social Media'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'Medium'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Continuous')),
    
    ('TrendHunter', 'https://www.trendhunter.com/', 
    (SELECT category_id FROM categories WHERE category_name = 'Trends'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'High'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Continuous')),
    
    ('Statista', 'https://www.statista.com/', 
    (SELECT category_id FROM categories WHERE category_name = 'Research'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'High'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Continuous')),
    
    ('Medium', 'https://medium.com/tag/trending', 
    (SELECT category_id FROM categories WHERE category_name = 'Blogs'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'Medium'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Daily')),
    
    ('Eventbrite', 'https://www.eventbrite.com/d/online/all-events/', 
    (SELECT category_id FROM categories WHERE category_name = 'Events'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'High'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Continuous')),
    
    ('Meetup', 'https://www.meetup.com/', 
    (SELECT category_id FROM categories WHERE category_name = 'Events'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'High'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Continuous')),
    
    ('Crunchbase', 'https://www.crunchbase.com/', 
    (SELECT category_id FROM categories WHERE category_name = 'Startups & Tech'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'High'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Continuous')),
    
    ('Forbes', 'https://www.forbes.com/', 
    (SELECT category_id FROM categories WHERE category_name = 'News'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'High'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Daily')),
    
    ('Buzzfeed', 'https://www.buzzfeed.com/', 
    (SELECT category_id FROM categories WHERE category_name = 'Entertainment'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'Medium'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Continuous')),
    
    ('StackOverflow', 'https://stackoverflow.com/questions/tagged/trending', 
    (SELECT category_id FROM categories WHERE category_name = 'Education & Research'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'High'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Daily')),
    
    ('Vimeo', 'https://vimeo.com/trending', 
    (SELECT category_id FROM categories WHERE category_name = 'Video Sharing'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'Medium'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Daily')),
    
    ('Dailymotion', 'https://www.dailymotion.com/us', 
    (SELECT category_id FROM categories WHERE category_name = 'Video Sharing'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'Medium'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Daily')),
    
    ('LiveJournal', 'https://www.livejournal.com/', 
    (SELECT category_id FROM categories WHERE category_name = 'Blogs'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'Medium'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Continuous')),
    
    ('Tumblr', 'https://www.tumblr.com/', 
    (SELECT category_id FROM categories WHERE category_name = 'Blogs'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'Medium'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Continuous')),
    
    ('Fark', 'https://www.fark.com/', 
    (SELECT category_id FROM categories WHERE category_name = 'News'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'Medium'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Daily')),
    
    ('TechCrunch', 'https://techcrunch.com/', 
    (SELECT category_id FROM categories WHERE category_name = 'Tech'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'High'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Daily')),
    
    ('Wired', 'https://www.wired.com/', 
    (SELECT category_id FROM categories WHERE category_name = 'Tech'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'High'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Daily')),
    
    ('The Verge', 'https://www.theverge.com/', 
    (SELECT category_id FROM categories WHERE category_name = 'Tech'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'High'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Daily')),
    
    ('CNET', 'https://www.cnet.com/', 
    (SELECT category_id FROM categories WHERE category_name = 'Tech'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'High'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Daily')),
    
    ('Gizmodo', 'https://gizmodo.com/', 
    (SELECT category_id FROM categories WHERE category_name = 'Tech'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'High'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Daily')),
    
    ('Business Insider', 'https://www.businessinsider.com/', 
    (SELECT category_id FROM categories WHERE category_name = 'News'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'High'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Daily')),
    
    ('Fast Company', 'https://www.fastcompany.com/', 
    (SELECT category_id FROM categories WHERE category_name = 'Business'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'High'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Daily')),
    
    ('Reuters', 'https://www.reuters.com/', 
    (SELECT category_id FROM categories WHERE category_name = 'News'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'High'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Daily')),
    
    ('Hacker News', 'https://news.ycombinator.com/', 
    (SELECT category_id FROM categories WHERE category_name = 'Tech'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'High'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Daily')),
    
    ('Vox', 'https://www.vox.com/', 
    (SELECT category_id FROM categories WHERE category_name = 'News'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'High'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Daily')),
    
    ('Mashable', 'https://mashable.com/', 
    (SELECT category_id FROM categories WHERE category_name = 'Entertainment'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'Medium'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Daily')),
    
    ('E! Online', 'https://www.eonline.com/', 
    (SELECT category_id FROM categories WHERE category_name = 'Entertainment'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'Medium'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Daily')),
    
    ('Entertainment Weekly', 'https://ew.com/', 
    (SELECT category_id FROM categories WHERE category_name = 'Entertainment'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'Medium'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Daily')),
    
    ('Polygon', 'https://www.polygon.com/', 
    (SELECT category_id FROM categories WHERE category_name = 'Entertainment'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'Medium'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Daily')),
    
    ('The Atlantic', 'https://www.theatlantic.com/', 
    (SELECT category_id FROM categories WHERE category_name = 'News'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'Medium'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Daily')),
    
    ('NPR', 'https://www.npr.org/', 
    (SELECT category_id FROM categories WHERE category_name = 'News'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'High'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Daily')),
    
    ('The Guardian', 'https://www.theguardian.com/', 
    (SELECT category_id FROM categories WHERE category_name = 'News'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'High'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Daily')),
    
    ('The New York Times', 'https://www.nytimes.com/', 
    (SELECT category_id FROM categories WHERE category_name = 'News'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'High'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Daily')),
    
    ('The Washington Post', 'https://www.washingtonpost.com/', 
    (SELECT category_id FROM categories WHERE category_name = 'News'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'High'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Daily')),
    
    ('CNN', 'https://www.cnn.com/', 
    (SELECT category_id FROM categories WHERE category_name = 'News'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'High'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Daily')),
    
    ('BBC News', 'https://www.bbc.com/news', 
    (SELECT category_id FROM categories WHERE category_name = 'News'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'High'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Daily')),
    
    ('ABC News', 'https://abcnews.go.com/', 
    (SELECT category_id FROM categories WHERE category_name = 'News'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'High'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Daily')),
    
    ('NBC News', 'https://www.nbcnews.com/', 
    (SELECT category_id FROM categories WHERE category_name = 'News'),
    (SELECT data_type_id FROM data_types WHERE data_type = 'Web'),
    (SELECT access_method_id FROM access_methods WHERE method_name = 'Free'),
    (SELECT reliability_id FROM reliability_levels WHERE level = 'High'),
    (SELECT freshness_id FROM freshness_levels WHERE freshness = 'Daily'));
    