INSERT INTO countries (country_code, country_name, region_code, region_name) VALUES
('AF', 'Afghanistan', 'AS', 'Asia'),
('AL', 'Albania', 'EU', 'Europe'),
('DZ', 'Algeria', 'AF', 'Africa'),
('AS', 'American Samoa', 'OC', 'Oceania'),
('AD', 'Andorra', 'EU', 'Europe'),
('AO', 'Angola', 'AF', 'Africa'),
('AI', 'Anguilla', 'NA', 'North America'),
('AQ', 'Antarctica', 'AN', 'Antarctica'),
('AG', 'Antigua and Barbuda', 'NA', 'North America'),
('AR', 'Argentina', 'SA', 'South America'),
('AM', 'Armenia', 'EU', 'Europe'),
('AW', 'Aruba', 'NA', 'North America'),
('AU', 'Australia', 'OC', 'Oceania'),
('AT', 'Austria', 'EU', 'Europe'),
('AZ', 'Azerbaijan', 'EU', 'Europe'),
('BS', 'Bahamas', 'NA', 'North America'),
('BH', 'Bahrain', 'AS', 'Asia'),
('BD', 'Bangladesh', 'AS', 'Asia'),
('BB', 'Barbados', 'NA', 'North America'),
('BY', 'Belarus', 'EU', 'Europe'),
('BE', 'Belgium', 'EU', 'Europe'),
('BZ', 'Belize', 'NA', 'North America'),
('BJ', 'Benin', 'AF', 'Africa'),
('BM', 'Bermuda', 'NA', 'North America'),
('BT', 'Bhutan', 'AS', 'Asia'),
('BO', 'Bolivia', 'SA', 'South America'),
('BA', 'Bosnia and Herzegovina', 'EU', 'Europe'),
('BW', 'Botswana', 'AF', 'Africa'),
('BR', 'Brazil', 'SA', 'South America'),
('IO', 'British Indian Ocean Territory', 'AF', 'Africa'),
('BN', 'Brunei Darussalam', 'AS', 'Asia'),
('BG', 'Bulgaria', 'EU', 'Europe'),
('BF', 'Burkina Faso', 'AF', 'Africa'),
('BI', 'Burundi', 'AF', 'Africa'),
('CV', 'Cabo Verde', 'AF', 'Africa'),
('KH', 'Cambodia', 'AS', 'Asia'),
('CM', 'Cameroon', 'AF', 'Africa'),
('CA', 'Canada', 'NA', 'North America'),
('KY', 'Cayman Islands', 'NA', 'North America'),
('CF', 'Central African Republic', 'AF', 'Africa'),
('TD', 'Chad', 'AF', 'Africa'),
('CL', 'Chile', 'SA', 'South America'),
('CN', 'China', 'AS', 'Asia'),
('CX', 'Christmas Island', 'OC', 'Oceania'),
('CC', 'Cocos (Keeling) Islands', 'OC', 'Oceania'),
('CO', 'Colombia', 'SA', 'South America'),
('KM', 'Comoros', 'AF', 'Africa'),
('CD', 'Congo, Democratic Republic of the', 'AF', 'Africa'),
('CG', 'Congo, Republic of the', 'AF', 'Africa'),
('CK', 'Cook Islands', 'OC', 'Oceania'),
('CR', 'Costa Rica', 'NA', 'North America'),
('HR', 'Croatia', 'EU', 'Europe'),
('CU', 'Cuba', 'NA', 'North America'),
('CW', 'Curaçao', 'NA', 'North America'),
('CY', 'Cyprus', 'EU', 'Europe'),
('CZ', 'Czech Republic', 'EU', 'Europe'),
('DK', 'Denmark', 'EU', 'Europe'),
('DJ', 'Djibouti', 'AF', 'Africa'),
('DM', 'Dominica', 'NA', 'North America'),
('DO', 'Dominican Republic', 'NA', 'North America'),
('EC', 'Ecuador', 'SA', 'South America'),
('EG', 'Egypt', 'AF', 'Africa'),
('SV', 'El Salvador', 'NA', 'North America'),
('GQ', 'Equatorial Guinea', 'AF', 'Africa'),
('ER', 'Eritrea', 'AF', 'Africa'),
('EE', 'Estonia', 'EU', 'Europe'),
('SZ', 'Eswatini', 'AF', 'Africa'),
('ET', 'Ethiopia', 'AF', 'Africa'),
('FK', 'Falkland Islands (Malvinas)', 'SA', 'South America'),
('FO', 'Faroe Islands', 'EU', 'Europe'),
('FJ', 'Fiji', 'OC', 'Oceania'),
('FI', 'Finland', 'EU', 'Europe'),
('FR', 'France', 'EU', 'Europe'),
('GF', 'French Guiana', 'SA', 'South America'),
('PF', 'French Polynesia', 'OC', 'Oceania'),
('GA', 'Gabon', 'AF', 'Africa'),
('GM', 'Gambia', 'AF', 'Africa'),
('GE', 'Georgia', 'EU', 'Europe'),
('DE', 'Germany', 'EU', 'Europe'),
('GH', 'Ghana', 'AF', 'Africa'),
('GI', 'Gibraltar', 'EU', 'Europe'),
('GR', 'Greece', 'EU', 'Europe'),
('GL', 'Greenland', 'NA', 'North America'),
('GD', 'Grenada', 'NA', 'North America'),
('GP', 'Guadeloupe', 'NA', 'North America'),
('GU', 'Guam', 'OC', 'Oceania'),
('GT', 'Guatemala', 'NA', 'North America'),
('GG', 'Guernsey', 'EU', 'Europe'),
('GN', 'Guinea', 'AF', 'Africa'),
('GW', 'Guinea-Bissau', 'AF', 'Africa'),
('GY', 'Guyana', 'SA', 'South America'),
('HT', 'Haiti', 'NA', 'North America'),
('HM', 'Heard Island and McDonald Islands', 'AN', 'Antarctica'),
('VA', 'Holy See', 'EU', 'Europe'),
('HN', 'Honduras', 'NA', 'North America'),
('HK', 'Hong Kong', 'AS', 'Asia'),
('HU', 'Hungary', 'EU', 'Europe'),
('IS', 'Iceland', 'EU', 'Europe'),
('IN', 'India', 'AS', 'Asia'),
('ID', 'Indonesia', 'AS', 'Asia'),
('IR', 'Iran', 'AS', 'Asia'),
('IQ', 'Iraq', 'AS', 'Asia'),
('IE', 'Ireland', 'EU', 'Europe'),
('IM', 'Isle of Man', 'EU', 'Europe'),
('IL', 'Israel', 'AS', 'Asia'),
('IT', 'Italy', 'EU', 'Europe'),
('JM', 'Jamaica', 'NA', 'North America'),
('JP', 'Japan', 'AS', 'Asia'),
('JE', 'Jersey', 'EU', 'Europe'),
('JO', 'Jordan', 'AS', 'Asia'),
('KZ', 'Kazakhstan', 'AS', 'Asia'),
('KE', 'Kenya', 'AF', 'Africa'),
('KI', 'Kiribati', 'OC', 'Oceania'),
('KP', 'Korea, Democratic People\'s Republic of', 'AS', 'Asia'),
('KR', 'Korea, Republic of', 'AS', 'Asia'),
('KW', 'Kuwait', 'AS', 'Asia'),
('KG', 'Kyrgyzstan', 'AS', 'Asia'),
('LA', 'Lao People\'s Democratic Republic', 'AS', 'Asia'),
('LV', 'Latvia', 'EU', 'Europe'),
('LB', 'Lebanon', 'AS', 'Asia'),
('LS', 'Lesotho', 'AF', 'Africa'),
('LR', 'Liberia', 'AF', 'Africa'),
('LY', 'Libya', 'AF', 'Africa'),
('LI', 'Liechtenstein', 'EU', 'Europe'),
('LT', 'Lithuania', 'EU', 'Europe'),
('LU', 'Luxembourg', 'EU', 'Europe'),
('MO', 'Macao', 'AS', 'Asia'),
('MG', 'Madagascar', 'AF', 'Africa'),
('MW', 'Malawi', 'AF', 'Africa'),
('MY', 'Malaysia', 'AS', 'Asia'),
('MV', 'Maldives', 'AS', 'Asia'),
('ML', 'Mali', 'AF', 'Africa'),
('MT', 'Malta', 'EU', 'Europe'),
('MH', 'Marshall Islands', 'OC', 'Oceania'),
('MQ', 'Martinique', 'NA', 'North America'),
('MR', 'Mauritania', 'AF', 'Africa'),
('MU', 'Mauritius', 'AF', 'Africa'),
('YT', 'Mayotte', 'AF', 'Africa'),
('MX', 'Mexico', 'NA', 'North America'),
('FM', 'Micronesia, Federated States of', 'OC', 'Oceania'),
('MD', 'Moldova', 'EU', 'Europe'),
('MC', 'Monaco', 'EU', 'Europe'),
('MN', 'Mongolia', 'AS', 'Asia'),
('ME', 'Montenegro', 'EU', 'Europe'),
('MS', 'Montserrat', 'NA', 'North America'),
('MA', 'Morocco', 'AF', 'Africa'),
('MZ', 'Mozambique', 'AF', 'Africa'),
('MM', 'Myanmar', 'AS', 'Asia'),
('NA', 'Namibia', 'AF', 'Africa'),
('NR', 'Nauru', 'OC', 'Oceania'),
('NP', 'Nepal', 'AS', 'Asia'),
('NL', 'Netherlands', 'EU', 'Europe'),
('NC', 'New Caledonia', 'OC', 'Oceania'),
('NZ', 'New Zealand', 'OC', 'Oceania'),
('NI', 'Nicaragua', 'NA', 'North America'),
('NE', 'Niger', 'AF', 'Africa'),
('NG', 'Nigeria', 'AF', 'Africa'),
('NU', 'Niue', 'OC', 'Oceania'),
('NF', 'Norfolk Island', 'OC', 'Oceania'),
('MP', 'Northern Mariana Islands', 'OC', 'Oceania'),
('NO', 'Norway', 'EU', 'Europe'),
('OM', 'Oman', 'AS', 'Asia'),
('PK', 'Pakistan', 'AS', 'Asia'),
('PW', 'Palau', 'OC', 'Oceania'),
('PS', 'Palestine, State of', 'AS', 'Asia'),
('PA', 'Panama', 'NA', 'North America'),
('PG', 'Papua New Guinea', 'OC', 'Oceania'),
('PY', 'Paraguay', 'SA', 'South America'),
('PE', 'Peru', 'SA', 'South America'),
('PH', 'Philippines', 'AS', 'Asia'),
('PN', 'Pitcairn', 'OC', 'Oceania'),
('PL', 'Poland', 'EU', 'Europe'),
('PT', 'Portugal', 'EU', 'Europe'),
('PR', 'Puerto Rico', 'NA', 'North America'),
('QA', 'Qatar', 'AS', 'Asia'),
('RE', 'Réunion', 'AF', 'Africa'),
('RO', 'Romania', 'EU', 'Europe'),
('RU', 'Russian Federation', 'EU', 'Europe'),
('RW', 'Rwanda', 'AF', 'Africa'),
('BL', 'Saint Barthélemy', 'NA', 'North America'),
('KN', 'Saint Kitts and Nevis', 'NA', 'North America'),
('LC', 'Saint Lucia', 'NA', 'North America'),
('MF', 'Saint Martin (French part)', 'NA', 'North America'),
('SX', 'Saint Martin (Dutch part)', 'NA', 'North America'),
('VC', 'Saint Vincent and the Grenadines', 'NA', 'North America'),
('WS', 'Samoa', 'OC', 'Oceania'),
('SM', 'San Marino', 'EU', 'Europe'),
('ST', 'Sao Tome and Principe', 'AF', 'Africa'),
('SA', 'Saudi Arabia', 'AS', 'Asia'),
('SN', 'Senegal', 'AF', 'Africa'),
('RS', 'Serbia', 'EU', 'Europe'),
('SC', 'Seychelles', 'AF', 'Africa'),
('SL', 'Sierra Leone', 'AF', 'Africa'),
('SG', 'Singapore', 'AS', 'Asia'),
('SX', 'Sint Maarten (Dutch part)', 'NA', 'North America'),
('SK', 'Slovakia', 'EU', 'Europe'),
('SI', 'Slovenia', 'EU', 'Europe'),
('SB', 'Solomon Islands', 'OC', 'Oceania'),
('SO', 'Somalia', 'AF', 'Africa'),
('ZA', 'South Africa', 'AF', 'Africa'),
('GS', 'South Georgia and the South Sandwich Islands', 'AN', 'Antarctica'),
('SS', 'South Sudan', 'AF', 'Africa'),
('ES', 'Spain', 'EU', 'Europe'),
('LK', 'Sri Lanka', 'AS', 'Asia'),
('SD', 'Sudan', 'AF', 'Africa'),
('SR', 'Suriname', 'SA', 'South America'),
('SJ', 'Svalbard and Jan Mayen', 'EU', 'Europe'),
('SZ', 'Sweden', 'EU', 'Europe'),
('CH', 'Switzerland', 'EU', 'Europe'),
('SY', 'Syrian Arab Republic', 'AS', 'Asia'),
('TW', 'Taiwan, Province of China', 'AS', 'Asia'),
('TJ', 'Tajikistan', 'AS', 'Asia'),
('TZ', 'Tanzania, United Republic of', 'AF', 'Africa'),
('TH', 'Thailand', 'AS', 'Asia'),
('TL', 'Timor-Leste', 'AS', 'Asia'),
('TG', 'Togo', 'AF', 'Africa'),
('TK', 'Tokelau', 'OC', 'Oceania'),
('TO', 'Tonga', 'OC', 'Oceania'),
('TT', 'Trinidad and Tobago', 'NA', 'North America'),
('TN', 'Tunisia', 'AF', 'Africa'),
('TR', 'Turkey', 'EU', 'Europe'),
('TM', 'Turkmenistan', 'AS', 'Asia'),
('TC', 'Turks and Caicos Islands', 'NA', 'North America'),
('TV', 'Tuvalu', 'OC', 'Oceania'),
('UG', 'Uganda', 'AF', 'Africa'),
('UA', 'Ukraine', 'EU', 'Europe'),
('AE', 'United Arab Emirates', 'AS', 'Asia'),
('GB', 'United Kingdom', 'EU', 'Europe'),
('US', 'United States of America', 'NA', 'North America'),
('UY', 'Uruguay', 'SA', 'South America'),
('UZ', 'Uzbekistan', 'AS', 'Asia'),
('VU', 'Vanuatu', 'OC', 'Oceania'),
('VE', 'Venezuela', 'SA', 'South America'),
('VN', 'Viet Nam', 'AS', 'Asia'),
('WF', 'Wallis and Futuna', 'OC', 'Oceania'),
('EH', 'Western Sahara', 'AF', 'Africa'),
('YE', 'Yemen', 'AS', 'Asia'),
('ZM', 'Zambia', 'AF', 'Africa'),
('ZW', 'Zimbabwe', 'AF', 'Africa');
